# Generated by Django 3.2 on 2021-05-16 16:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=api.models.gen_code, max_length=10, unique=True),
        ),
    ]
