# Generated by Django 3.2 on 2021-05-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_files_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_url',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
